# Generated by Django 2.1.5 on 2019-03-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190214_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
